In [1]:
import pandas as pd

In [2]:
data=pd.read_excel('astrotrain.xlsx')

In [6]:
data.head()

,SUBSURVEY,SNID,IAUC,FAKE,RA,DECL,PIXSIZE,NXPIX,NYPIX,CCDNUM,...,SIM_PEAKMAG_z,SIM_EXPOSURE_g,SIM_EXPOSURE_r,SIM_EXPOSURE_i,SIM_EXPOSURE_z,SIM_GALFRAC_g,SIM_GALFRAC_r,SIM_GALFRAC_i,SIM_GALFRAC_z,SIM_SUBSAMPLE_INDEX
0,,10473255,NULL,2,53.468451,-28.349424,0.27,-9,-9,44,...,23.664705,1,1,1,1,2.378913e+00,1.384469,1.228777,1.400711,-9
1,,2110040,NULL,2,53.508185,-28.470810,0.27,-9,-9,50,...,24.363064,1,1,1,1,3.254097e-14,7.968017,3.885829,3.697690,-9
2,,9966178,NULL,2,35.077432,-6.979272,0.27,-9,-9,51,...,23.319248,1,1,1,1,5.848331e-01,0.558739,0.499326,0.525232,-9
3,,19732134,NULL,2,52.852204,-27.184372,0.27,-9,-9,3,...,22.917084,1,1,1,1,4.299130e+00,13.111013,19.559818,34.610160,-9
4,,1582526,NULL,2,36.932302,-5.248342,0.27,-9,-9,55,...,22.626780,1,1,1,1,2.718171e-01,0.285706,0.416343,0.543132,-9

In [9]:
#printing the unique instances in last column
print(data['SIM_SUBSAMPLE_INDEX'].unique())

[-9]